# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02a05da3ae09045082575e8c04df2d71157944ee19aaae1670f60a2a5f467a4b2f00398b6303dcdae27f739863a9ee128678032ca7dc3d32c501be8ce118dc5a

test:
  secret_key_base: c13f1f43368a3048fc7319261cdb8b7c479c3a79be57114d917c0120059b0f3a04fc1913cdcacf3fedf540c4ab9b209bf12932dc87e7ecb01d9bae7d493d7493

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
